version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/vscode-extension"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/mcp/graph-ui"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/mcp/claude-desktop-extension"
    schedule:
      interval: "weekly"
